-- DO NOT MANUALLY EDIT THIS FILE!
-- THIS FILE IS AUTOMATICALLY GENERATED AND ALL CHANGES WILL BE OVERWRITTEN
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use ieee.numeric_std.ALL;

entity adder is
port(
	in0: in std_logic_vector(4 downto 1);
	in1: in std_logic_vector(4 downto 1);
	out0: out std_logic_vector(4 downto 1));
end adder;

architecture behaviour_adder of adder is
begin

out0 <= std_logic_vector(unsigned(in0) + unsigned(in1));

end behaviour_adder;